### ISSUE TITLE
Clojure 11 warnings

### ISSUE THREAD

**Issue by timothypratley** [r0man/noencore#3]
Clojure 1.11.0-beta1 adds `parse-long` and `parse-double`, causing the following:

```
WARNING: parse-long already refers to: #'clojure.core/parse-long in namespace: no.en.core, being replaced by: #'no.en.core/parse-long
WARNING: parse-double already refers to: #'clojure.core/parse-double in namespace: no.en.core, being replaced by: #'no.en.core/parse-double
```

I think the easiest way to address would be to add
`(:refer-clojure :exclude [parse-long parse-double])` to the ns declaration of `no.en.core`

**Comment by logseq-cldwalker** [comment]
Also encountering this with clojurescript 1.11.54. @r0man Would you be open to a PR for this?

**Comment by r0man** [comment]
Hi, sorry, I did not see this. Should be fixed in master.

**Comment by timothypratley** [comment]
Thank you :)

**Comment by logseq-cldwalker** [comment]
Thanks!
